### ISSUE TITLE
Multi GPU worker

### ISSUE THREAD

**Issue by mkabatek** [huo-ju/dfserver#2]
Hello,

I'm interested in contributing to this repo to enable multiGPU workers. I have a machine that I can use to test. Please let me know what I can to do help move the process forward. Thanks

**Comment by huo-ju** [comment]
Hi, my apologies for missing this issue. Thank your for the offer, but this is a opensource software to help anyone can build a GPU pool and share resources with friends. We didn't have a public GPU pool. Thanks!
